/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectFrames;

//import java.awt.Toolkit;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import projectFrames.*;
/**
 *
 * @author Chessman
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */
    public LoginFrame() {
        initComponents();
        setVisible(true);
        setAlwaysOnTop(true);
        Toolkit t = Toolkit.getDefaultToolkit();
        int w = (int)t.getScreenSize().getWidth();
        int h = (int)t.getScreenSize().getHeight();
        setSize(w, h);
        //setExtendedState(MAXIMIZED_BOTH);
        System.out.println(w);
        System.out.println(h);
    }
    
    //Validation
    public boolean validateLogin(){
    String Name = username.getText();
    String Password = password.getText();
    
        if (Name.equals("")){
        JOptionPane.showMessageDialog(this, "Enter a username!");
        return false;
        } 
        if (Password.equals("")){
        JOptionPane.showMessageDialog(this, "Enter a password!");
        return false;
        } 
        return true;
    }
    
    public void login(){
        String Name = username.getText();
        String Password = password.getText();
        
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
            PreparedStatement pst = con.prepareStatement(sql);
        
            pst.setString(1,Name);
            pst.setString(2, Password);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
                JOptionPane.showMessageDialog(this, "Login Successfully");
                HomePage home = new HomePage(Name);
                home.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
            }
        } catch (Exception e){
            e.printStackTrace();
        }   
    }

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        cvsuheader2 = new javax.swing.JLabel();
        cvsuLogoPlaceholder = new javax.swing.JLabel();
        cvsuheader1 = new javax.swing.JLabel();
        cvsuheader3 = new javax.swing.JLabel();
        closeIcon = new javax.swing.JLabel();
        lPanelContainer = new RoundedPanel.RoundPanel();
        loginheader = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        username = new app.bolivia.swing.JCTextField();
        userIcon = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        login = new rojerusan.RSMaterialButtonCircle();
        register = new rojerusan.RSMaterialButtonCircle();
        password = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JLabel();
        loginheaderwelcome = new javax.swing.JLabel();
        fPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cavite State University Silang-Campus Library Management System Copyright 2023-2024");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(51, 102, 0));

        cvsuheader2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        cvsuheader2.setForeground(new java.awt.Color(255, 255, 255));
        cvsuheader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvsuheader2.setText("Library Management System");

        cvsuLogoPlaceholder.setBackground(new java.awt.Color(255, 255, 255));
        cvsuLogoPlaceholder.setForeground(new java.awt.Color(255, 255, 255));
        cvsuLogoPlaceholder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvsuLogoPlaceholder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LogoCvsu_enhanced (1).png"))); // NOI18N

        cvsuheader1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        cvsuheader1.setForeground(new java.awt.Color(255, 255, 255));
        cvsuheader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvsuheader1.setText("Cavite State University");

        cvsuheader3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        cvsuheader3.setForeground(new java.awt.Color(255, 255, 255));
        cvsuheader3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvsuheader3.setText("Silang Campus");

        closeIcon.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        closeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/circle-xmark.png"))); // NOI18N
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
        });

        lPanelContainer.setBackground(new java.awt.Color(255, 255, 204));
        lPanelContainer.setRoundBottomLeft(20);
        lPanelContainer.setRoundBottomRight(20);
        lPanelContainer.setRoundTopLeft(20);
        lPanelContainer.setRoundTopRight(20);

        loginheader.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        loginheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginheader.setText("Log In to your account");

        passwordLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password");

        passwordIcon.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        passwordIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password-lock.png"))); // NOI18N

        username.setBackground(new java.awt.Color(255, 255, 204));
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 102, 0)));
        username.setFocusCycleRoot(true);
        username.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        username.setPlaceholder("Enter Username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        userIcon.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/id-card-clip-alt.png"))); // NOI18N

        usernameLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username");

        login.setBackground(new java.awt.Color(51, 102, 0));
        login.setText("Log In");
        login.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(255, 255, 204));
        register.setForeground(new java.awt.Color(0, 0, 0));
        register.setText("Register Account");
        register.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(255, 255, 204));
        password.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 102, 0)));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        showPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png"))); // NOI18N
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showPasswordMouseReleased(evt);
            }
        });

        loginheaderwelcome.setFont(new java.awt.Font("Monotype Corsiva", 1, 60)); // NOI18N
        loginheaderwelcome.setForeground(new java.awt.Color(51, 102, 0));
        loginheaderwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginheaderwelcome.setText("Welcome");

        fPass.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        fPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/unlock.png"))); // NOI18N
        fPass.setText("Forgot Password");
        fPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        fPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lPanelContainerLayout = new javax.swing.GroupLayout(lPanelContainer);
        lPanelContainer.setLayout(lPanelContainerLayout);
        lPanelContainerLayout.setHorizontalGroup(
            lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lPanelContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginheader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginheaderwelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(250, 250, 250))
            .addGroup(lPanelContainerLayout.createSequentialGroup()
                .addGroup(lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lPanelContainerLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lPanelContainerLayout.createSequentialGroup()
                                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lPanelContainerLayout.createSequentialGroup()
                                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lPanelContainerLayout.createSequentialGroup()
                                .addComponent(passwordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lPanelContainerLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameLabel)
                                    .addComponent(passwordLabel)))))
                    .addGroup(lPanelContainerLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(fPass)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        lPanelContainerLayout.setVerticalGroup(
            lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lPanelContainerLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(loginheaderwelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginheader)
                .addGap(60, 60, 60)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(lPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(fPass)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(cvsuLogoPlaceholder, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(cvsuheader3)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(cvsuheader1)
                        .addGap(52, 52, 52))
                    .addComponent(cvsuheader2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(135, 135, 135)
                .addComponent(lPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(cvsuLogoPlaceholder, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cvsuheader1)
                        .addGap(5, 5, 5)
                        .addComponent(cvsuheader3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cvsuheader2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 870));
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if (validateLogin()){
            login();
        }
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        SignUpFrame sign = new SignUpFrame();
        sign.setVisible(true);
        dispose();
    }//GEN-LAST:event_registerActionPerformed

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMousePressed
        password.setEchoChar((char)0);
    }//GEN-LAST:event_showPasswordMousePressed

    private void showPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMouseReleased
       password.setEchoChar('*');
    }//GEN-LAST:event_showPasswordMouseReleased

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost

    }//GEN-LAST:event_passwordFocusLost

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost

    }//GEN-LAST:event_usernameFocusLost

    private void fPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fPassMouseClicked
        ForgotPassword f = new ForgotPassword();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_fPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JLabel cvsuLogoPlaceholder;
    private javax.swing.JLabel cvsuheader1;
    private javax.swing.JLabel cvsuheader2;
    private javax.swing.JLabel cvsuheader3;
    private javax.swing.JLabel fPass;
    private RoundedPanel.RoundPanel lPanelContainer;
    private rojerusan.RSMaterialButtonCircle login;
    private javax.swing.JLabel loginheader;
    private javax.swing.JLabel loginheaderwelcome;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel passwordLabel;
    private rojerusan.RSMaterialButtonCircle register;
    private javax.swing.JLabel showPassword;
    private javax.swing.JLabel userIcon;
    private app.bolivia.swing.JCTextField username;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
