/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectFrames;

//import java.awt.Toolkit;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import projectFrames.*;
/**
 *
 * @author Chessman
 */
public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */
    public SignUpFrame() {
        initComponents();
        setVisible(true);
        setAlwaysOnTop(true);
        Toolkit t = Toolkit.getDefaultToolkit();
        int w = (int)t.getScreenSize().getWidth();
        int h = (int)t.getScreenSize().getHeight();
        setSize(w, h);
        //setExtendedState(MAXIMIZED_BOTH);
        System.out.println(w);
        System.out.println(h);
    }

    //method to insert data into users table
    public void insertRegisterDetails(){
        String Email = email.getText();
        String Name = username.getText();
        String Password = password.getText();
        String RQuestion = recQComboBox.getSelectedItem().toString();
        String RAnswer = recAnswer.getText();
    
        try {
            Connection con = DBConnection.getConnection();
            String sql = "INSERT INTO users(username,password,email,question,answer) VALUES(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
        
            pst.setString(1,Name);
            pst.setString(2, Password);
            pst.setString(3, Email);
            pst.setString(4, RQuestion);
            pst.setString(5, RAnswer);

            int updatedRowCount = pst.executeUpdate();
            if (updatedRowCount > 0){
                JOptionPane.showMessageDialog(this, "Registered Successfully!");
                LoginFrame page = new LoginFrame();
                page.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "An error occured, please try again.");
            }
        } catch (Exception e){
            e.printStackTrace();
        }   
    }
    
    //Validation
    public boolean validateRegistration(){
        String Email = email.getText();
        String Name = username.getText();
        String Password = password.getText();
        String RQuestion = recQComboBox.getSelectedItem().toString();
        String RAnswer = recAnswer.getText();
        
        if (Email.equals("") || !Email.matches("^.+@.+\\..+$")){
            JOptionPane.showMessageDialog(this, "Enter a valid email");
            return false;
        }
        if (Name.equals("")){
            JOptionPane.showMessageDialog(this, "Enter a username");
            return false;
        }if (Password.equals("")){
            JOptionPane.showMessageDialog(this, "Enter a password");
            return false;
        }if (RAnswer.equals("")){
            JOptionPane.showMessageDialog(this, "Enter a recovery answer");
            return false;
        }
        return true;
    }
    
    //Check Duplication of Username (tried both but didnt work)
    public boolean checkDuplicateUser(){
        String Name = username.getText();
        boolean isExists = false;
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM users WHERE username = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, Name);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExists = true;
            } else {
                isExists = false;
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return isExists;
    }
    
    //Check Duplicate Email
    public boolean checkDuplicateEmail(){
        String Email = email.getText();
        boolean isExists = false;
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM users WHERE email = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, Email);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExists = true;
            } else {
                isExists = false;
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return isExists;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        cvsuheader2 = new javax.swing.JLabel();
        cvsuLogoPlaceholder = new javax.swing.JLabel();
        cvsuheader1 = new javax.swing.JLabel();
        cvsuheader3 = new javax.swing.JLabel();
        rPanelContainer = new RoundedPanel.RoundPanel();
        regHeader = new javax.swing.JLabel();
        email = new app.bolivia.swing.JCTextField();
        emailLabel = new javax.swing.JLabel();
        emailIcon = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        username = new app.bolivia.swing.JCTextField();
        userIcon = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameLabel2 = new javax.swing.JLabel();
        userIcon4 = new javax.swing.JLabel();
        recQComboBox = new javax.swing.JComboBox<>();
        passwordIcon1 = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        recAnswer = new app.bolivia.swing.JCTextField();
        login = new rojerusan.RSMaterialButtonCircle();
        register = new rojerusan.RSMaterialButtonCircle();
        password = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        closeIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cavite State University Silang-Campus Library Management System Copyright 2023-2024");
        setName("signUpFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setBackground(new java.awt.Color(51, 102, 0));

        cvsuheader2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        cvsuheader2.setForeground(new java.awt.Color(255, 255, 255));
        cvsuheader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvsuheader2.setText("Library Management System");

        cvsuLogoPlaceholder.setBackground(new java.awt.Color(255, 255, 255));
        cvsuLogoPlaceholder.setForeground(new java.awt.Color(255, 255, 255));
        cvsuLogoPlaceholder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvsuLogoPlaceholder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LogoCvsu_enhanced (1).png"))); // NOI18N

        cvsuheader1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        cvsuheader1.setForeground(new java.awt.Color(255, 255, 255));
        cvsuheader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvsuheader1.setText("Cavite State University");

        cvsuheader3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        cvsuheader3.setForeground(new java.awt.Color(255, 255, 255));
        cvsuheader3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvsuheader3.setText("Silang Campus");

        rPanelContainer.setBackground(new java.awt.Color(255, 255, 204));
        rPanelContainer.setRoundBottomLeft(20);
        rPanelContainer.setRoundBottomRight(20);
        rPanelContainer.setRoundTopLeft(20);
        rPanelContainer.setRoundTopRight(20);

        regHeader.setFont(new java.awt.Font("Monotype Corsiva", 1, 60)); // NOI18N
        regHeader.setForeground(new java.awt.Color(51, 102, 0));
        regHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regHeader.setText("Register Account");

        email.setBackground(new java.awt.Color(255, 255, 204));
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 102, 0)));
        email.setFocusCycleRoot(true);
        email.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        email.setPlaceholder("Enter your CvSU Email/Email");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Create your account here");

        emailIcon.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        emailIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/envelope (4).png"))); // NOI18N

        passwordLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password");

        passwordIcon.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        passwordIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password-lock.png"))); // NOI18N

        username.setBackground(new java.awt.Color(255, 255, 204));
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 102, 0)));
        username.setFocusCycleRoot(true);
        username.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        username.setPlaceholder("Enter Username");
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        userIcon.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/id-card-clip-alt.png"))); // NOI18N

        usernameLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username");

        usernameLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        usernameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel2.setText("Recovery Question");

        userIcon4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        userIcon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user-question.png"))); // NOI18N

        recQComboBox.setBackground(new java.awt.Color(255, 255, 204));
        recQComboBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        recQComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your pet name?", "When is the month of your birthdate?", "Where is your birthplace?", "What is your childhood nickname?", "Who is your favorite teacher?" }));
        recQComboBox.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 102, 0)));

        passwordIcon1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        passwordIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/answer-alt.png"))); // NOI18N

        passwordLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        passwordLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel1.setText("Recovery Answer");

        recAnswer.setBackground(new java.awt.Color(255, 255, 204));
        recAnswer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 102, 0)));
        recAnswer.setFocusCycleRoot(true);
        recAnswer.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        recAnswer.setPlaceholder("Enter Recovery Answer");
        recAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recAnswerActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(255, 255, 204));
        login.setForeground(new java.awt.Color(0, 0, 0));
        login.setText("Log In");
        login.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(51, 102, 0));
        register.setText("Register Account");
        register.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(255, 255, 204));
        password.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 102, 0)));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        showPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eye.png"))); // NOI18N
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showPasswordMouseReleased(evt);
            }
        });

        emailLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        emailLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel1.setText("CVSU Email");

        javax.swing.GroupLayout rPanelContainerLayout = new javax.swing.GroupLayout(rPanelContainer);
        rPanelContainer.setLayout(rPanelContainerLayout);
        rPanelContainerLayout.setHorizontalGroup(
            rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rPanelContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(rPanelContainerLayout.createSequentialGroup()
                .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rPanelContainerLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rPanelContainerLayout.createSequentialGroup()
                                .addComponent(passwordIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rPanelContainerLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(passwordLabel1))
                            .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(rPanelContainerLayout.createSequentialGroup()
                                    .addComponent(userIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(recQComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(rPanelContainerLayout.createSequentialGroup()
                                    .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rPanelContainerLayout.createSequentialGroup()
                                    .addComponent(emailIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rPanelContainerLayout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameLabel2)
                                        .addComponent(passwordLabel)
                                        .addComponent(usernameLabel))))
                            .addGroup(rPanelContainerLayout.createSequentialGroup()
                                .addComponent(passwordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(rPanelContainerLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(regHeader))
                    .addGroup(rPanelContainerLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(emailLabel)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rPanelContainerLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(363, Short.MAX_VALUE)))
            .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rPanelContainerLayout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(emailLabel1)
                    .addContainerGap(481, Short.MAX_VALUE)))
        );
        rPanelContainerLayout.setVerticalGroup(
            rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rPanelContainerLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(regHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(password))
                .addGap(18, 18, 18)
                .addComponent(usernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userIcon4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(recQComboBox))
                .addGap(18, 18, 18)
                .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rPanelContainerLayout.createSequentialGroup()
                    .addContainerGap(666, Short.MAX_VALUE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)))
            .addGroup(rPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rPanelContainerLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(593, Short.MAX_VALUE)))
        );

        closeIcon.setBackground(new java.awt.Color(255, 255, 255));
        closeIcon.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        closeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/circle-xmark.png"))); // NOI18N
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeIconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(cvsuLogoPlaceholder, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(cvsuheader3)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addComponent(cvsuheader1)
                        .addGap(52, 52, 52))
                    .addComponent(cvsuheader2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(135, 135, 135)
                .addComponent(rPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(closeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(cvsuLogoPlaceholder, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cvsuheader1)
                        .addGap(5, 5, 5)
                        .addComponent(cvsuheader3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cvsuheader2))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(rPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 870));
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void recAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recAnswerActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        LoginFrame page = new LoginFrame();
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        if (validateRegistration() == true){
            if (checkDuplicateUser() == false){
                insertRegisterDetails();
                email.setText("");
                username.setText("");
                password.setText("");
                recQComboBox.setSelectedIndex(0);
                recAnswer.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Account already exist.");
            }
        }        
    }//GEN-LAST:event_registerActionPerformed

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeIconMouseClicked

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if (checkDuplicateEmail() == true){
            JOptionPane.showMessageDialog(this, "Email already exist.");
            email.setText("");
        }
    }//GEN-LAST:event_emailFocusLost

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        if (checkDuplicateUser() == true){
            JOptionPane.showMessageDialog(this, "Username already exist.");
            username.setText("");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMousePressed
        password.setEchoChar((char)0);
    }//GEN-LAST:event_showPasswordMousePressed

    private void showPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMouseReleased
        password.setEchoChar('*');
    }//GEN-LAST:event_showPasswordMouseReleased

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost

    }//GEN-LAST:event_passwordFocusLost

    private void closeIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_closeIconMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JLabel cvsuLogoPlaceholder;
    private javax.swing.JLabel cvsuheader1;
    private javax.swing.JLabel cvsuheader2;
    private javax.swing.JLabel cvsuheader3;
    private app.bolivia.swing.JCTextField email;
    private javax.swing.JLabel emailIcon;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private rojerusan.RSMaterialButtonCircle login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel passwordIcon1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private RoundedPanel.RoundPanel rPanelContainer;
    private app.bolivia.swing.JCTextField recAnswer;
    private javax.swing.JComboBox<String> recQComboBox;
    private javax.swing.JLabel regHeader;
    private rojerusan.RSMaterialButtonCircle register;
    private javax.swing.JLabel showPassword;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userIcon4;
    private app.bolivia.swing.JCTextField username;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel2;
    // End of variables declaration//GEN-END:variables
}
